# Generated by Django 2.2.2 on 2019-06-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20190617_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='person_name',
        ),
    ]
